name: learing_firebase_using_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  google_sign_in: ^6.2.1
  
  image_picker: ^1.1.2
  image_cropper: ^7.1.0

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

